exports.lodash = require('lodash')
exports.ramda = require('ramda')
exports.gulpComplexity = require('gulp-complexity')
exports.inquirer = require('inquirer')
exports.gulp = require('gulp')
exports.underscore = require('underscore')
exports.yeoman = require('yeoman-generator')
